### ISSUE TITLE
IOS 8.0 deprecations

### ISSUE THREAD

**Issue by olexth** [stanislaw/AFNetworkingLogger#5]
Looks line all calls -dataFromPropertyList:format:errorDescritpion in AFNetworkingLogGenerator needs to be updated with -dataWithPropertyList:format:options:error: for iOS 8.x support

Warning description:
'dataFromPropertyList:format:errorDescription:' is deprecated: first deprecated in iOS 8.0 - Use dataWithPropertyList:format:options:error: instead.

**Comment by stanislaw** [comment]
@alexth, I've just released 0.0.17 with this change. Feel free to upgrade :smiley:
